server:
  port: 8082

spring:
  application:
    name: "Tracker-task"

  datasource:
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task-db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true